def upgrade():
    # ### commands auto-generated by Alembic from actual SQLAlchemy models ###

    # organizations
    op.create_table(
        'organizations',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('name', sa.VARCHAR(255), nullable=False, autoincrement=True,
            sa.Column('slug', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('is_active', sa.BOOLEAN, nullable=False, server_default=ScalarElementColumnDefault(True), autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('updated_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    )

    # departments
    op.create_table(
        'departments',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('name', sa.VARCHAR(150), nullable=False, autoincrement=True,
            sa.Column('code', sa.VARCHAR(50), nullable=False, autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
    )

    # roles
    op.create_table(
        'roles',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('name', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('description', sa.VARCHAR, nullable=True, autoincrement=True,
            sa.Column('is_system_role', sa.BOOLEAN, nullable=False, server_default=ScalarElementColumnDefault(False), autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
    )

    # permissions
    op.create_table(
        'permissions',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('name', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('description', sa.VARCHAR, nullable=True, autoincrement=True,
            sa.Column('category', sa.VARCHAR(50), nullable=False, autoincrement=True,
    )

    # role_permissions
    op.create_table(
        'role_permissions',
    sa.Column('role_id', sa.UUID, nullable=False, primary_key=True, autoincrement=True,
            sa.Column('permission_id', sa.UUID, nullable=False, primary_key=True, autoincrement=True,
    sa.ForeignKeyKey('id', 'permissions', ondelete='CASCADE')
            sa.ForeignKeyKey('id', 'roles', ondelete='CASCADE')
    )

    # users
    op.create_table(
        'users',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('department_id', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('email', sa.VARCHAR(255), nullable=False, autoincrement=True,
            sa.Column('hashed_password', sa.VARCHAR(255), nullable=False, autoincrement=True,
            sa.Column('full_name', sa.VARCHAR(255), nullable=False, autoincrement=True,
            sa.Column('role_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('is_active', sa.BOOLEAN, nullable=False, server_default=ScalarElementColumnDefault(True), autoincrement=True,
            sa.Column('is_verified', sa.BOOLEAN, nullable=False, server_default=ScalarElementColumnDefault(False), autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('updated_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
            sa.ForeignKeyKey('id', 'roles', None)
            sa.ForeignKeyKey('id', 'departments', ondelete='SET NULL')
    )

    # integrations
    op.create_table(
        'integrations',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('service_name', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('is_enabled', sa.BOOLEAN, nullable=False, server_default=ScalarElementColumnDefault(True), autoincrement=True,
            sa.Column('config_encrypted', sa.TEXT, nullable=False, autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('updated_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
    )

    # documents
    op.create_table(
        'documents',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('uploaded_by', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('file_name', sa.VARCHAR(255), nullable=False, autoincrement=True,
            sa.Column('file_path', sa.TEXT, nullable=False, autoincrement=True,
            sa.Column('file_type', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('file_size_bytes', sa.BIGINT, nullable=False, autoincrement=True,
            sa.Column('checksum_sha256', sa.VARCHAR(64), nullable=False, autoincrement=True,
            sa.Column('processing_status', sa.VARCHAR(50), nullable=False, server_default=ScalarElementColumnDefault('PENDING'), autoincrement=True,
            sa.Column('metadata', sa.JSONB, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('updated_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'users', ondelete='SET NULL')
            sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
    )

    # document_chunks
    op.create_table(
        'document_chunks',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('document_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('chunk_index', sa.INTEGER, nullable=False, autoincrement=True,
            sa.Column('content', sa.TEXT, nullable=False, autoincrement=True,
            sa.Column('token_count', sa.INTEGER, nullable=False, autoincrement=True,
            sa.Column('embedding', sa.VECTOR(1536), nullable=True, autoincrement=True,
            sa.Column('metadata', sa.JSONB, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
            sa.ForeignKeyKey('id', 'documents', ondelete='CASCADE')
    )

    # conversations
    op.create_table(
        'conversations',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('user_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('title', sa.VARCHAR(255), nullable=False, autoincrement=True,
            sa.Column('agent_type', sa.VARCHAR(50), nullable=False, server_default=ScalarElementColumnDefault('SUPERVISOR'), autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('updated_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'users', ondelete='CASCADE')
            sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
    )

    # messages
    op.create_table(
        'messages',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('conversation_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('sender_type', sa.VARCHAR(50), nullable=False, autoincrement=True,
            sa.Column('content', sa.TEXT, nullable=False, autoincrement=True,
            sa.Column('citations', sa.JSONB, nullable=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('metadata', sa.JSONB, nullable=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'conversations', ondelete='CASCADE')
    )

    # agent_runs
    op.create_table(
        'agent_runs',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('conversation_id', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('user_id', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('agent_name', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('task_description', sa.TEXT, nullable=False, autoincrement=True,
            sa.Column('status', sa.VARCHAR(50), nullable=False, server_default=ScalarElementColumnDefault('STARTED'), autoincrement=True,
            sa.Column('started_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('completed_at', sa.DATETIME, nullable=True, autoincrement=True,
            sa.Column('latency_ms', sa.INTEGER, nullable=True, autoincrement=True,
            sa.Column('total_tokens', sa.INTEGER, nullable=False, server_default=ScalarElementColumnDefault(0), autoincrement=True,
            sa.Column('cost_usd', sa.NUMERIC(10, 6)(10, 6), nullable=False, server_default=ScalarElementColumnDefault(0.0), autoincrement=True,
            sa.Column('error_message', sa.TEXT, nullable=True, autoincrement=True,
    sa.ForeignKeyKey('id', 'conversations', ondelete='SET NULL')
            sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
            sa.ForeignKeyKey('id', 'users', ondelete='SET NULL')
    )

    # tool_calls
    op.create_table(
        'tool_calls',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('agent_run_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('tool_name', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('input_parameters', sa.JSONB, nullable=False, autoincrement=True,
            sa.Column('output_result', sa.JSONB, nullable=True, autoincrement=True,
            sa.Column('risk_level', sa.VARCHAR(20), nullable=False, server_default=ScalarElementColumnDefault('LOW'), autoincrement=True,
            sa.Column('requires_approval', sa.BOOLEAN, nullable=False, server_default=ScalarElementColumnDefault(False), autoincrement=True,
            sa.Column('approval_id', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('status', sa.VARCHAR(50), nullable=False, server_default=ScalarElementColumnDefault('PENDING'), autoincrement=True,
            sa.Column('executed_at', sa.DATETIME, nullable=True, autoincrement=True,
            sa.Column('execution_latency_ms', sa.INTEGER, nullable=True, autoincrement=True,
    sa.ForeignKeyKey('id', 'agent_runs', ondelete='CASCADE')
    )

    # approvals
    op.create_table(
        'approvals',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('agent_run_id', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('workflow_run_id', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('action_type', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('risk_level', sa.VARCHAR(20), nullable=False, autoincrement=True,
            sa.Column('action_payload', sa.JSONB, nullable=False, autoincrement=True,
            sa.Column('reason', sa.TEXT, nullable=False, autoincrement=True,
            sa.Column('status', sa.VARCHAR(50), nullable=False, server_default=ScalarElementColumnDefault('PENDING'), autoincrement=True,
            sa.Column('requested_by', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('decided_by', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('decision_reason', sa.TEXT, nullable=True, autoincrement=True,
            sa.Column('decided_at', sa.DATETIME, nullable=True, autoincrement=True,
            sa.Column('signature_hmac', sa.VARCHAR(128), nullable=True, autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
            sa.ForeignKeyKey('id', 'workflow_runs', ondelete='SET NULL')
            sa.ForeignKeyKey('id', 'agent_runs', ondelete='SET NULL')
            sa.ForeignKeyKey('id', 'users', ondelete='SET NULL')
            sa.ForeignKeyKey('id', 'users', ondelete='SET NULL')
    )

    # audit_logs
    op.create_table(
        'audit_logs',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('user_id', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('event_type', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('resource_type', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('resource_id', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('ip_address', sa.VARCHAR(45), nullable=True, autoincrement=True,
            sa.Column('details', sa.JSONB, nullable=False, autoincrement=True,
            sa.Column('entry_hash', sa.VARCHAR(64), nullable=False, autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
            sa.ForeignKeyKey('id', 'users', ondelete='SET NULL')
    )

    # workflows
    op.create_table(
        'workflows',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('created_by', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('name', sa.VARCHAR(255), nullable=False, autoincrement=True,
            sa.Column('description', sa.TEXT, nullable=True, autoincrement=True,
            sa.Column('trigger_type', sa.VARCHAR(50), nullable=False, autoincrement=True,
            sa.Column('trigger_config', sa.JSONB, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('graph_definition', sa.JSONB, nullable=False, autoincrement=True,
            sa.Column('is_active', sa.BOOLEAN, nullable=False, server_default=ScalarElementColumnDefault(True), autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('updated_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'users', ondelete='SET NULL')
            sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
    )

    # workflow_runs
    op.create_table(
        'workflow_runs',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('workflow_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('status', sa.VARCHAR(50), nullable=False, server_default=ScalarElementColumnDefault('PENDING'), autoincrement=True,
            sa.Column('current_step', sa.VARCHAR(100), nullable=True, server_default=ScalarElementColumnDefault('1'), autoincrement=True,
            sa.Column('input_payload', sa.JSONB, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('output_payload', sa.JSONB, nullable=True, autoincrement=True,
            sa.Column('started_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('finished_at', sa.DATETIME, nullable=True, autoincrement=True,
            sa.Column('error_details', sa.TEXT, nullable=True, autoincrement=True,
    sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
            sa.ForeignKeyKey('id', 'workflows', ondelete='CASCADE')
    )

    # actions
    op.create_table(
        'actions',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('requested_by', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('action_type', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('risk_level', sa.VARCHAR(20), nullable=False, autoincrement=True,
            sa.Column('status', sa.VARCHAR(50), nullable=False, server_default=ScalarElementColumnDefault('PENDING'), autoincrement=True,
            sa.Column('idempotency_key', sa.VARCHAR(128), nullable=True, autoincrement=True,
            sa.Column('input_hash', sa.VARCHAR(64), nullable=True, autoincrement=True,
            sa.Column('input_payload', sa.JSONB, nullable=False, autoincrement=True,
            sa.Column('result_payload', sa.JSONB, nullable=True, autoincrement=True,
            sa.Column('error_message', sa.TEXT, nullable=True, autoincrement=True,
            sa.Column('external_reference', sa.VARCHAR(255), nullable=True, autoincrement=True,
            sa.Column('verified', sa.BOOLEAN, nullable=False, server_default=ScalarElementColumnDefault(False), autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('updated_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('completed_at', sa.DATETIME, nullable=True, autoincrement=True,
    sa.ForeignKeyKey('id', 'users', ondelete='SET NULL')
            sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
    )

    # action_approvals
    op.create_table(
        'action_approvals',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('action_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('requested_by', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('action_type', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('payload_summary', sa.TEXT, nullable=False, autoincrement=True,
            sa.Column('risk_level', sa.VARCHAR(20), nullable=False, autoincrement=True,
            sa.Column('status', sa.VARCHAR(50), nullable=False, server_default=ScalarElementColumnDefault('PENDING'), autoincrement=True,
            sa.Column('payload_hash', sa.VARCHAR(64), nullable=False, autoincrement=True,
            sa.Column('approved_by', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('approved_at', sa.DATETIME, nullable=True, autoincrement=True,
            sa.Column('rejected_at', sa.DATETIME, nullable=True, autoincrement=True,
            sa.Column('expires_at', sa.DATETIME, nullable=False, autoincrement=True,
            sa.Column('decision_reason', sa.TEXT, nullable=True, autoincrement=True,
            sa.Column('signature_hmac', sa.VARCHAR(128), nullable=True, autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('updated_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'users', ondelete='SET NULL')
            sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
            sa.ForeignKeyKey('id', 'actions', ondelete='CASCADE')
            sa.ForeignKeyKey('id', 'users', ondelete='SET NULL')
    )

    # action_audit_logs
    op.create_table(
        'action_audit_logs',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('user_id', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('action_id', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('action_type', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('event_type', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('status', sa.VARCHAR(50), nullable=False, autoincrement=True,
            sa.Column('risk_level', sa.VARCHAR(20), nullable=False, autoincrement=True,
            sa.Column('request_id', sa.VARCHAR(100), nullable=True, autoincrement=True,
            sa.Column('approval_id', sa.VARCHAR(100), nullable=True, autoincrement=True,
            sa.Column('external_reference', sa.VARCHAR(255), nullable=True, autoincrement=True,
            sa.Column('details', sa.JSONB, nullable=False, autoincrement=True,
            sa.Column('entry_hash', sa.VARCHAR(64), nullable=False, autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'users', ondelete='SET NULL')
            sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
    )

    # machines
    op.create_table(
        'machines',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('name', sa.VARCHAR(150), nullable=False, autoincrement=True,
            sa.Column('machine_code', sa.VARCHAR(50), nullable=False, autoincrement=True,
            sa.Column('department_id', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('status', sa.VARCHAR(50), nullable=False, server_default=ScalarElementColumnDefault('OPERATIONAL')),
            sa.Column('failure_count', sa.INTEGER, nullable=False, server_default=ScalarElementColumnDefault(0)),
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('updated_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'departments', ondelete='SET NULL')
            sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
    )

    # production_records
    op.create_table(
        'production_records',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('machine_id', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('batch_number', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('status', sa.VARCHAR(50), nullable=False, server_default=ScalarElementColumnDefault('PASSED'), autoincrement=True,
            sa.Column('defect_count', sa.INTEGER, nullable=False, server_default=ScalarElementColumnDefault(0), autoincrement=True,
            sa.Column('production_time_hours', sa.NUMERIC(10, 2)(10, 2), nullable=False, server_default=ScalarElementColumnDefault(0.0), autoincrement=True,
            sa.Column('notes', sa.TEXT, nullable=True, autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'machines', ondelete='SET NULL')
            sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
    )

    # orders
    op.create_table(
        'orders',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('order_number', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('customer_name', sa.VARCHAR(255), nullable=False, autoincrement=True,
            sa.Column('status', sa.VARCHAR(50), nullable=False, server_default=ScalarElementColumnDefault('PENDING'), autoincrement=True,
            sa.Column('total_amount', sa.NUMERIC(12, 2)(12, 2), nullable=False, server_default=ScalarElementColumnDefault(0.0), autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('updated_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
    )

    # products
    op.create_table(
        'products',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('name', sa.VARCHAR(255), nullable=False, autoincrement=True,
            sa.Column('sku', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('category', sa.VARCHAR(100), nullable=False, autoincrement=True,
            sa.Column('price', sa.NUMERIC(10, 2)(10, 2), nullable=False, server_default=ScalarElementColumnDefault(0.0), autoincrement=True,
            sa.Column('usage_count', sa.INTEGER, nullable=False, server_default=ScalarElementColumnDefault(0), autoincrement=True,
            sa.Column('is_active', sa.BOOLEAN, nullable=False, server_default=ScalarElementColumnDefault(True), autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
    )

    # vendors
    op.create_table(
        'vendors',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('name', sa.VARCHAR(255), nullable=False, autoincrement=True,
            sa.Column('contact_email', sa.VARCHAR(255), nullable=True, autoincrement=True,
            sa.Column('total_purchases', sa.NUMERIC(14, 2)(14, 2), nullable=False, server_default=ScalarElementColumnDefault(0.0), autoincrement=True,
            sa.Column('rating', sa.NUMERIC(3, 2)(3, 2), nullable=False, server_default=ScalarElementColumnDefault(5.0), autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
    )

    # maintenance_requests
    op.create_table(
        'maintenance_requests',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('machine_id', sa.UUID, nullable=True, autoincrement=True,
            sa.Column('title', sa.VARCHAR(255), nullable=False, autoincrement=True,
            sa.Column('status', sa.VARCHAR(50), nullable=False, server_default=ScalarElementColumnDefault('OPEN'), autoincrement=True,
            sa.Column('priority', sa.VARCHAR(20), nullable=False, server_default=ScalarElementColumnDefault('MEDIUM'), autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
            sa.ForeignKeyKey('id', 'machines', ondelete='SET NULL')
    )

    # notifications
    op.create_table(
        'notifications',
    sa.Column('id', sa.UUID, nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
            sa.Column('organization_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('user_id', sa.UUID, nullable=False, autoincrement=True,
            sa.Column('title', sa.VARCHAR(255), nullable=False, autoincrement=True,
            sa.Column('message', sa.TEXT, nullable=False, autoincrement=True,
            sa.Column('notification_type', sa.VARCHAR(50), nullable=False, autoincrement=True,
            sa.Column('is_read', sa.BOOLEAN, nullable=False, server_default=ScalarElementColumnDefault(False), autoincrement=True,
            sa.Column('link_url', sa.TEXT, nullable=True, autoincrement=True,
            sa.Column('created_at', sa.DATETIME, nullable=False, server_default=sa.text('gen_random_uuid()'), autoincrement=True,
    sa.ForeignKeyKey('id', 'organizations', ondelete='CASCADE')
            sa.ForeignKeyKey('id', 'users', ondelete='CASCADE')
    )

def downgrade():
    # ### commands auto-generated by Alembic from actual SQLAlchemy models ###
    # Tables dropped in reverse order of creation

    op.drop_table('notifications')
    op.drop_table('maintenance_requests')
    op.drop_table('vendors')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('production_records')
    op.drop_table('machines')
    op.drop_table('action_audit_logs')
    op.drop_table('action_approvals')
    op.drop_table('actions')
    op.drop_table('workflow_runs')
    op.drop_table('workflows')
    op.drop_table('audit_logs')
    op.drop_table('approvals')
    op.drop_table('tool_calls')
    op.drop_table('agent_runs')
    op.drop_table('messages')
    op.drop_table('conversations')
    op.drop_table('document_chunks')
    op.drop_table('documents')
    op.drop_table('integrations')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('permissions')
    op.drop_table('roles')
    op.drop_table('departments')
    op.drop_table('organizations')

    # ### end Alembic commands ###